name: Manually triggered workflow 1
'on':
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true
        default: Mona the Octocat
      home:
        description: Location
        required: false
        default: The Octoverse
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ inputs.name }}!"
          echo "I am in ${{ inputs.home }}!"
  SleepForSomeSeconds:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30s
        shell: bash
  say_hello_again:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ inputs.name }}!"
          echo "I am in ${{ inputs.home }}!"
